# Generated by Django 5.0 on 2024-03-05 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place_aze', '0002_loggedinuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
