# Generated by Django 5.0 on 2024-03-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place_aze', '0004_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='otp',
        ),
    ]
