# Generated by Django 5.0 on 2024-03-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_aze', '0007_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('qUid', models.BigAutoField(primary_key=True, serialize=False)),
                ('testId', models.CharField(max_length=20)),
                ('qId', models.CharField(max_length=25)),
                ('q', models.TextField()),
                ('a', models.CharField(max_length=100)),
                ('b', models.CharField(max_length=100)),
                ('c', models.CharField(max_length=100)),
                ('d', models.CharField(max_length=100)),
                ('ans', models.CharField(max_length=10)),
                ('marks', models.IntegerField()),
                ('teacherId', models.BigIntegerField()),
            ],
        ),
    ]
