# Generated by Django 5.0 on 2024-03-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_aze', '0008_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('tUid', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('testId', models.CharField(max_length=100)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('show_ans', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('teacherId', models.BigIntegerField()),
            ],
        ),
    ]
