# Generated by Django 5.0 on 2024-03-11 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place_aze', '0009_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='show_ans',
        ),
    ]
