# Generated by Django 5.0 on 2024-03-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_aze', '0010_remove_test_show_ans'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAns',
            fields=[
                ('saUid', models.BigAutoField(primary_key=True, serialize=False)),
                ('qUid', models.BigIntegerField()),
                ('testId', models.CharField(max_length=20)),
                ('stid', models.IntegerField()),
                ('markedAns', models.CharField(max_length=10)),
                ('ans', models.CharField(max_length=10)),
                ('marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentResults',
            fields=[
                ('srUid', models.BigAutoField(primary_key=True, serialize=False)),
                ('stid', models.IntegerField()),
                ('testId', models.CharField(max_length=20)),
                ('scoredMarks', models.IntegerField()),
                ('submitDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
