# Generated by Django 5.0 on 2024-03-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place_aze', '0011_studentans_studentresults'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
