# Generated by Django 4.2.6 on 2024-03-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place_aze', '0015_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
