# Generated by Django 4.2.6 on 2024-03-20 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place_aze', '0017_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAns',
        ),
        migrations.DeleteModel(
            name='StudentResults',
        ),
    ]
